### get all students
GET http://localhost:5000/students?page=1&limit=5


### get a student by id
GET http://localhost:5000/students/4


### create a student
POST http://localhost:5000/students
Content-Type: application/json

{
    "name": "Ossama Zain",
    "email": "ossama.zain@example.com",
    "age": 20,
    "gender": "male"
}


### update a student
PUT http://localhost:5000/students/1
Content-Type: application/json

{
    "name": "Ossama Zain",
    "email": "ossama.zain@example.com",
    "age": 20,
    "gender": "male"
}


### delete a student
DELETE http://localhost:5000/students/8